### ISSUE TITLE
Suite du readme

### ISSUE THREAD

**Issue by hyphaene** [MeXaaR/boilerplate-meteor-react#1]
Hello !

La suite du readme pourrait indiquer qu'il faut entrer des infos dans le fichier firstuser.js

Y'a également des requêtes qui bloquent si y'a des ablockers, tout roule en navigation privée cela dit.

Merci pour le taff et la présentation en meetup en tout cas ;)

**Comment by MeXaaR** [comment]
ouai tu as raison, j'dois le finir ce readme, jle fais assez vite en effet

merci
